### ISSUE TITLE
Can't wmake beamWeldFoam (OF6/10) on WSL

### ISSUE THREAD

**Issue by MaximilianNast** [tomflint22/beamWeldFoam#12]
Hi,

when installing beamWeldFoam using Ubuntu on Windows Subsystem for Linux i've been running into the same Problem with both the OF6 and OF10 branch. Every time there is some problem with "CorrectPhi.H". Maybe someone has seen this before and has an idea on how to fix this? Could it be that this just doesn't work on WSL?

In both cases i have confirmed that my OpenFOAM installation is working by running one of the examples. 

I have included error logs below, hoping someone could take a look at what might be going wrong since i can't figure it out. 

**Thanks for any answers in advance!**

---

OpenFOAM 6 / Ubuntu 18.04.6 LTS  on WSL / beamWeldFoam main branch
wmake produces:
```
In file included from beamWeldFoam.C:52:0:
CorrectPhi.H:2:1: error: expected constructor, destructor, or type conversion before ‘(’ token
 (
 ^
In file included from CorrectPhi.H:11:0,
                 from beamWeldFoam.C:52:
/opt/openfoam6/src/finiteVolume/lnInclude/continuityErrs.H:32:1: error: expected unqualified-id before ‘{’ token
 {
 ^
In file included from initCorrectPhi.H:19:0,
                 from beamWeldFoam.C:75:
correctPhi.H: In function ‘int main(int, char**)’:
correctPhi.H:1:1: error: ‘CorrectPhi’ was not declared in this scope
 CorrectPhi
 ^~~~~~~~~~
correctPhi.H:1:1: note: suggested alternative: ‘correctPhi’
 CorrectPhi
 ^~~~~~~~~~
 correctPhi
In file included from beamWeldFoam.C:75:0:
initCorrectPhi.H:23:5: error: ‘CorrectPhi’ was not declared in this scope
     CorrectPhi
     ^~~~~~~~~~
initCorrectPhi.H:23:5: note: suggested alternative: ‘correctPhi’
     CorrectPhi
     ^~~~~~~~~~
     correctPhi
/opt/openfoam6/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/beamWeldFoam.o' failed
make: *** [Make/linux64GccDPInt32Opt/beamWeldFoam.o] Error 1
```
---

OpenFOAM 10 / Ubuntu 18.04.6 LTS on WSL / beamWeldFoam OF10 branch
wmake produces:
```
In file included from beamweldFoam.C:54:
CorrectPhi.H:3:1: error: ‘phi’ does not name a type
    3 | phi = mesh.Sf() & Uf();
      | ^~~
CorrectPhi.H:5:15: error: expected constructor, destructor, or type conversion before ‘(’ token
    5 | correctUphiBCs(U, phi, true);
      |               ^
CorrectPhi.H:7:1: error: expected unqualified-id before ‘if’
    7 | if (divU.valid())
      | ^~
CorrectPhi.H:20:1: error: expected unqualified-id before ‘else’
   20 | else
      | ^~~~
In file included from CorrectPhi.H:34,
                 from beamweldFoam.C:54:
/opt/openfoam10/src/finiteVolume/lnInclude/continuityErrs.H:32:1: error: expected unqualified-id before ‘{’ token
   32 | {
      | ^
In file included from beamweldFoam.C:54:
CorrectPhi.H:37:18: error: expected constructor, destructor, or type conversion before ‘(’ token
   37 | fvc::makeRelative(phi, U);
      |                  ^
In file included from beamweldFoam.C:78:
initCorrectPhi.H: In function ‘int main(int, char**)’:
initCorrectPhi.H:23:9: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
   23 |         correctUphiBCs(U, phi, true);
      |         ^~~~~~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:25:9: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   25 |         CorrectPhi
      |         ^~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:38:9: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
   38 |         correctUphiBCs(U, phi, true);
      |         ^~~~~~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:40:9: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   40 |         CorrectPhi
      |         ^~~~~~~~~~
      |         correctPhi
In file included from beamweldFoam.C:174:
correctPhi.H:5:1: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
    5 | correctUphiBCs(U, phi, true);
      | ^~~~~~~~~~~~~~
      | correctPhi
correctPhi.H:9:5: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
    9 |     CorrectPhi
      |     ^~~~~~~~~~
      |     correctPhi
correctPhi.H:22:5: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   22 |     CorrectPhi
      |     ^~~~~~~~~~
      |     correctPhi
make: *** [/opt/openfoam10/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/beamweldFoam.o] Error 1
```

**Comment by tomflint22** [comment]
Hi,

Yes I think the WSL doesn’t work for new solvers. A few people have tried and failed to install on windows, you’d be better making an Ubuntu partition on your hard disk.

All the best,

Tom

Sent from my iPhone

On 10 Aug 2023, at 13:05, Maximilian Nast ***@***.***> wrote:

﻿

Hi,

when installing beamWeldFoam using Ubuntu on Windows Subsystem for Linux i've been running into the same Problem with both the OF6 and OF10 branch. Every time there is some problem with "CorrectPhi.H". Maybe someone has seen this before and has an idea on how to fix this? Could it be that this just doesn't work on WSL?

In both cases i have confirmed that my OpenFOAM installation is working by running one of the examples.

I have included error logs below, hoping someone could take a look at what might be going wrong since i can't figure it out.

Thanks for any answers in advance!

________________________________

OpenFOAM 6 / Ubuntu 18.04.6 LTS on WSL / beamWeldFoam main branch
wmake produces:

In file included from beamWeldFoam.C:52:0:
CorrectPhi.H:2:1: error: expected constructor, destructor, or type conversion before ‘(’ token
 (
 ^
In file included from CorrectPhi.H:11:0,
                 from beamWeldFoam.C:52:
/opt/openfoam6/src/finiteVolume/lnInclude/continuityErrs.H:32:1: error: expected unqualified-id before ‘{’ token
 {
 ^
In file included from initCorrectPhi.H:19:0,
                 from beamWeldFoam.C:75:
correctPhi.H: In function ‘int main(int, char**)’:
correctPhi.H:1:1: error: ‘CorrectPhi’ was not declared in this scope
 CorrectPhi
 ^~~~~~~~~~
correctPhi.H:1:1: note: suggested alternative: ‘correctPhi’
 CorrectPhi
 ^~~~~~~~~~
 correctPhi
In file included from beamWeldFoam.C:75:0:
initCorrectPhi.H:23:5: error: ‘CorrectPhi’ was not declared in this scope
     CorrectPhi
     ^~~~~~~~~~
initCorrectPhi.H:23:5: note: suggested alternative: ‘correctPhi’
     CorrectPhi
     ^~~~~~~~~~
     correctPhi
/opt/openfoam6/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/beamWeldFoam.o' failed
make: *** [Make/linux64GccDPInt32Opt/beamWeldFoam.o] Error 1


________________________________

OpenFOAM 10 / Ubuntu 18.04.6 LTS on WSL / beamWeldFoam OF10 branch
wmake produces:

In file included from beamweldFoam.C:54:
CorrectPhi.H:3:1: error: ‘phi’ does not name a type
    3 | phi = mesh.Sf() & Uf();
      | ^~~
CorrectPhi.H:5:15: error: expected constructor, destructor, or type conversion before ‘(’ token
    5 | correctUphiBCs(U, phi, true);
      |               ^
CorrectPhi.H:7:1: error: expected unqualified-id before ‘if’
    7 | if (divU.valid())
      | ^~
CorrectPhi.H:20:1: error: expected unqualified-id before ‘else’
   20 | else
      | ^~~~
In file included from CorrectPhi.H:34,
                 from beamweldFoam.C:54:
/opt/openfoam10/src/finiteVolume/lnInclude/continuityErrs.H:32:1: error: expected unqualified-id before ‘{’ token
   32 | {
      | ^
In file included from beamweldFoam.C:54:
CorrectPhi.H:37:18: error: expected constructor, destructor, or type conversion before ‘(’ token
   37 | fvc::makeRelative(phi, U);
      |                  ^
In file included from beamweldFoam.C:78:
initCorrectPhi.H: In function ‘int main(int, char**)’:
initCorrectPhi.H:23:9: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
   23 |         correctUphiBCs(U, phi, true);
      |         ^~~~~~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:25:9: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   25 |         CorrectPhi
      |         ^~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:38:9: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
   38 |         correctUphiBCs(U, phi, true);
      |         ^~~~~~~~~~~~~~
      |         correctPhi
initCorrectPhi.H:40:9: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   40 |         CorrectPhi
      |         ^~~~~~~~~~
      |         correctPhi
In file included from beamweldFoam.C:174:
correctPhi.H:5:1: error: ‘correctUphiBCs’ was not declared in this scope; did you mean ‘correctPhi’?
    5 | correctUphiBCs(U, phi, true);
      | ^~~~~~~~~~~~~~
      | correctPhi
correctPhi.H:9:5: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
    9 |     CorrectPhi
      |     ^~~~~~~~~~
      |     correctPhi
correctPhi.H:22:5: error: ‘CorrectPhi’ was not declared in this scope; did you mean ‘correctPhi’?
   22 |     CorrectPhi
      |     ^~~~~~~~~~
      |     correctPhi
make: *** [/opt/openfoam10/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/beamweldFoam.o] Error 1

**Comment by MaximilianNast** [comment]
Thanks for the quick reply! I'll do that then.

**Comment by micheleiacopo** [comment]
Hello, 
I'm writing here because I'm indeed working in WSL, but i'm not sure that the error I get is related to it.

I'm using openFOAM10 and when I issue the wmake command I receive the following errors:
```
mizz@A0042972:~/OpenFOAM/mizz-10/beamWeldFoam/applications/solvers/beamWeldFoam$ wmake
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/twoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/incompressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/interfaceProperties/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/TurbulenceModels/turbulenceModels/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/TurbulenceModels/incompressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/immiscibleIncompressibleTwoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/dynamicFvMesh/ does not exist
Making dependency list for source file beamWeldFoam.C
could not open file dynamicFvMesh.H for source file beamWeldFoam.C due to No such file or directory
could not open file immiscibleIncompressibleTwoPhaseMixture.H for source file beamWeldFoam.C due to No such file or directory
could not open file turbulentTransportModel.H for source file beamWeldFoam.C due to No such file or directory
could not open file fvOptions.H for source file beamWeldFoam.C due to No such file or directory
could not open file createDynamicFvMesh.H for source file beamWeldFoam.C due to No such file or directory
could not open file alphaControls.H for source file beamWeldFoam.C due to No such file or directory
could not open file createFvOptions.H for source file beamWeldFoam.C due to No such file or directory
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I./VoF -I/opt/openfoam10/src/transportModels/twoPhaseMixture/lnInclude -I/opt/openfoam10/src/transportModels -I/opt/openfoam10/src/transportModels/incompressible/lnInclude -I/opt/openfoam10/src/transportModels/interfaceProperties/lnInclude -I/opt/openfoam10/src/TurbulenceModels/turbulenceModels/lnInclude -I/opt/openfoam10/src/TurbulenceModels/incompressible/lnInclude -I/opt/openfoam10/src/transportModels/immiscibleIncompressibleTwoPhaseMixture/lnInclude -I/opt/openfoam10/src/finiteVolume/lnInclude -I/opt/openfoam10/src/dynamicFvMesh/lnInclude -I/opt/openfoam10/src/meshTools/lnInclude -I/opt/openfoam10/src/sampling/lnInclude -IlnInclude -I. -I/opt/openfoam10/src/OpenFOAM/lnInclude -I/opt/openfoam10/src/OSspecific/POSIX/lnInclude   -fPIC -c beamWeldFoam.C -o Make/linux64GccDPInt32Opt/beamWeldFoam.o
beamWeldFoam.C:42:10: fatal error: dynamicFvMesh.H: No such file or directory
   42 | #include "dynamicFvMesh.H"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/openfoam10/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/beamWeldFoam.o] Error 1
```
It seems that some folders/files are missing or not found from the openFOAM libraries.
Have you ever faced this problem? Thanks

**Comment by tomflint22** [comment]
Hi,

Yes the solver won’t compile on WSL. Best to install an ubuntu partition on your machine.

All the best

On 21 Sep 2023, at 14:03, micheleiacopo ***@***.***> wrote:



Hello,
I'm writing here because I'm indeed working in WSL, but i'm not sure that the error I get is related to it.

I'm using openFOAM10 and when I issue the wmake command I receive the following errors:

***@***.***:~/OpenFOAM/mizz-10/beamWeldFoam/applications/solvers/beamWeldFoam$ wmake
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/twoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/incompressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/interfaceProperties/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/TurbulenceModels/turbulenceModels/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/TurbulenceModels/incompressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/transportModels/immiscibleIncompressibleTwoPhaseMixture/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam10/src/dynamicFvMesh/ does not exist
Making dependency list for source file beamWeldFoam.C
could not open file dynamicFvMesh.H for source file beamWeldFoam.C due to No such file or directory
could not open file immiscibleIncompressibleTwoPhaseMixture.H for source file beamWeldFoam.C due to No such file or directory
could not open file turbulentTransportModel.H for source file beamWeldFoam.C due to No such file or directory
could not open file fvOptions.H for source file beamWeldFoam.C due to No such file or directory
could not open file createDynamicFvMesh.H for source file beamWeldFoam.C due to No such file or directory
could not open file alphaControls.H for source file beamWeldFoam.C due to No such file or directory
could not open file createFvOptions.H for source file beamWeldFoam.C due to No such file or directory
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I./VoF -I/opt/openfoam10/src/transportModels/twoPhaseMixture/lnInclude -I/opt/openfoam10/src/transportModels -I/opt/openfoam10/src/transportModels/incompressible/lnInclude -I/opt/openfoam10/src/transportModels/interfaceProperties/lnInclude -I/opt/openfoam10/src/TurbulenceModels/turbulenceModels/lnInclude -I/opt/openfoam10/src/TurbulenceModels/incompressible/lnInclude -I/opt/openfoam10/src/transportModels/immiscibleIncompressibleTwoPhaseMixture/lnInclude -I/opt/openfoam10/src/finiteVolume/lnInclude -I/opt/openfoam10/src/dynamicFvMesh/lnInclude -I/opt/openfoam10/src/meshTools/lnInclude -I/opt/openfoam10/src/sampling/lnInclude -IlnInclude -I. -I/opt/openfoam10/src/OpenFOAM/lnInclude -I/opt/openfoam10/src/OSspecific/POSIX/lnInclude   -fPIC -c beamWeldFoam.C -o Make/linux64GccDPInt32Opt/beamWeldFoam.o
beamWeldFoam.C:42:10: fatal error: dynamicFvMesh.H: No such file or directory
   42 | #include "dynamicFvMesh.H"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/openfoam10/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/beamWeldFoam.o] Error 1


It seems that some folders/filme are missing or not found from the openFOAM libraries.
Have you ever faced this problem? Thanks

**Comment by micheleiacopo** [comment]
Still unsure about the missing files/forder errors I got when trying bWF OF10 + OF10 on Windows 10 22H2 + WSL2.
But...wmake without errors of beamWeldFoam main branch + OpenFOAM6 on the same WSL !

**Comment by tomflint22** [comment]
Hi,

sorry I dont use windows. I know that WSL doesnt really work very well. 

If you want to use our solvers: beamweldFoam, laserbeamFoam, and any others we'll be releasing soon, then I suggest you make an ubuntu partition in your hard disk so you can boot into ubuntu directly. It's incredibly easy to install our solvers in linux.

All the best,
Tom
