### ISSUE TITLE
HeatSource vs domain decomposition

### ISSUE THREAD

**Issue by micheleiacopo** [tomflint22/beamWeldFoam#13]
Hello, thank you for your work.

I'm testing your code on an EBW-like case which involves the heat source.
I've noticed that when the domain is split into sub-domains for parallelisation and a separation exist which is normal to the beam direction, the projection algorithm seems to identify such separation surface even if a real air-to-metal border has been identified upstream. (see fig)
![image](https://github.com/tomflint22/beamWeldFoam/assets/145599496/5fea0816-2df1-404e-b549-a3e51bdbcad4)

**Comment by tomflint22** [comment]
Hi,

yes you have to decompose the domain so that there are no boundaries in the y-direction. We talk about this in the SoftwareX paper. 

Our more recent ray-tracing code doesn't have this issue:

https://doi.org/10.1016/j.softx.2022.101299


If I get chance I'll modify the beamweldfoam algorithm using what we implemented in laserbeamFoam.

For now, just make sure your mesh is made up of decomposed columns (no processor boundaries normal to the y-direction axis).

I'll leave this open, and try and get round to it in the new year

**Comment by tomflint22** [comment]
So just to clarify, you can decompose the domain any way you like with laserbeamFoam (or any of the solvers in the laserbeamfoam repository). I learnt a lot about MPI since implementing the beamweldfoam heat deposition algorithm :)

**Comment by micheleiacopo** [comment]
Thanks for your quick replies. 

Yes, it is indeed specified in the companion article:
> However, the current implementation of the heat source model is limited to a Cartesian, fully structured, mesh. To avoid any potential error in the heat source implementation due to decomposition, it is recommended not to split the domains along the direction of the beam.
I read it at the beginning, but I forgot this detail meanwhile. 

Nice to know that it is solved/implemented in the new solvers, thanks!
Do also the new solvers need a Cartesian, fully structured, mesh?

**Comment by tomflint22** [comment]
I've not actually tried the new laser beam foam solver on anything other than Cartesian grids actually. In theory the algorithm should work but maybe how the rays are initialised will need tweaking.

I always use orthogonal grids as the spurious currents are less with these type of grids as the interface curvature calculation for the csf surface tension is better with orthogonal, so you get less spurious currents.

We have a phase field version of this code actually (as opposed to the vof) for the multiphase treatment, so that doesn't matter the type of grid so at some point I'll make sure the algorithm works on unstructured.
For the current implementation though with vof, I would recommend using Cartesian grids, but as I say you can decompose these any way you wish with laserbeamfoam

**Comment by micheleiacopo** [comment]
Hello, 

It seems that, in some  scenarios, even if no division exists in the y direction, some problem arises in the projection of the heat sources (right side in the following picture)
![image](https://github.com/tomflint22/beamWeldFoam/assets/145599496/fa56f871-6b10-4930-b577-542de3202f08)

**Comment by tomflint22** [comment]
Is it the source term that you think is incorrect? The beam profile is displayed through the whole domain and looks correct to me.

If you can share a (quick) case that reproduces this I'll try and look into it. We haven't had any issues. Are you sure that there is no over-lap of processors? You can open each processor in paraFoam to check.

Thanks,

Tom

**Comment by micheleiacopo** [comment]
Yes, it is, the sourceTerm which should be the result of the projection of the beam profile if I'm not wrong.

I have some "stepped" border between adjacent domains, but no overlap, i.e., every element is only in one domain.
![image](https://github.com/tomflint22/beamWeldFoam/assets/145599496/b3a50800-6478-4baa-81d4-8a160aed7c8b)
![image](https://github.com/tomflint22/beamWeldFoam/assets/145599496/352f0bbc-6bd0-439e-8535-e1fa112a91b9)

There is indeed a correlation between the presence of the steps and the missing parts of the projection...
![image](https://github.com/tomflint22/beamWeldFoam/assets/145599496/4b889ee3-70c3-4eb7-96c7-0ba4851db9d0)

**Comment by tomflint22** [comment]
No, sorry, that is enough to mess the algorithm up

**Comment by tomflint22** [comment]
There cantt be any processor boundaries in the y direction for beamweldfoam to work in parallel. I think what I'll do is wrap beamweldfoam into the laserbeamFoam repository. We have a 'hyperboloid' heat source in a branch there that will give the hour-glass profile. I'll try and do this in the next few weeks but I'm super busy ATM

**Comment by tomflint22** [comment]
For now, you can either use laserbeamFoam for your case (you could edit the absorptivity so it's just 1). Or use beamweldfoam and make sure there are no processor boundaries in the y direction

**Comment by micheleiacopo** [comment]
Your replies actually anticipated my next question :)
Thank you.
